name: Main2

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Dump UID & GID
      run: |
        echo User ID [UID]: $(id -u)
        echo Group ID [GID]: $(id -g)
